[package]
name = "wildfly_meta"
version = "0.4.0"
authors = ["Harald Pehl <harald.pehl@gmail.com>"]
edition = "2021"
description = "A library for WildFly metadata: container images, feature packs, and version expression parsing"
readme = "README.md"
homepage = "https://github.com/hpehl/wildfly-meta"
repository = "https://github.com/hpehl/wildfly-meta"
license = "Apache-2.0"
keywords = ["WildFly", "container", "image", "feature-pack", "version"]

[dependencies]
anyhow = "1.0.102"
regex = "1.12.3"
reqwest = { version = "0.13.3", features = ["blocking"] }
semver = { version = "1.0.28", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"

[lib]
name = "wildfly_meta"
path = "src/lib.rs"
