config_version = 2

[[feature_packs]]
shortcut = "ai"
name = "AI"
group_id = "org.wildfly.generative-ai"
artifact_id = "wildfly-ai-feature-pack"
versions = [
  { version = "0.9.1", maven_version = "0.9.1" },
  { version = "0.9.0", maven_version = "0.9.0" },
  { version = "0.8.1", maven_version = "0.8.1" },
]

[[feature_packs]]
shortcut = "graphql"
name = "GraphQL"
group_id = "org.wildfly.extras.graphql"
artifact_id = "wildfly-microprofile-graphql-feature-pack"
versions = [
  { version = "2.7.0", maven_version = "2.7.0.Final" },
  { version = "2.6.0", maven_version = "2.6.0.Final" },
  { version = "2.5.0", maven_version = "2.5.0.Final" },
]

[[feature_packs]]
shortcut = "grpc"
name = "gRPC"
group_id = "org.wildfly.extras.grpc"
artifact_id = "wildfly-grpc-feature-pack"
versions = [
  { version = "0.1.16", maven_version = "0.1.16.Final" },
  { version = "0.1.15", maven_version = "0.1.15.Final" },
  { version = "0.1.14", maven_version = "0.1.14.Final" },
]

[[feature_packs]]
shortcut = "keycloak"
name = "Keycloak"
group_id = "org.keycloak"
artifact_id = "keycloak-saml-adapter-galleon-pack"
versions = [
  { version = "26.6.1", maven_version = "26.6.1" },
  { version = "26.6.0", maven_version = "26.6.0" },
  { version = "26.5.7", maven_version = "26.5.7" },
]

[[feature_packs]]
shortcut = "myfaces"
name = "MyFaces"
group_id = "org.wildfly"
artifact_id = "wildfly-myfaces-feature-pack"
versions = [
  { version = "2.0.3", maven_version = "2.0.3.Final" },
  { version = "2.0.2", maven_version = "2.0.2.Final" },
  { version = "2.0.0", maven_version = "2.0.0.Final" },
]

[[feature_packs]]
shortcut = "vertx"
name = "Vertx"
group_id = "org.wildfly.extras.vertx"
artifact_id = "wildfly-vertx-feature-pack"
versions = [
  { version = "1.0.2", maven_version = "1.0.2.Final" },
  { version = "1.0.1", maven_version = "1.0.1.Final" },
  { version = "1.0.0", maven_version = "1.0.0.Final" },
]
