config_version = 2

[[wildfly_images]]
major = 10
minor = 0
version = "10.0.0"
release_version = "10.0.0.Final"
core_version = "2.0.10"
core_release_version = "2.0.10.Final"
image_tag = "10.0.0.Final"
repository = "docker.io/jboss/wildfly"
platforms = []

[[wildfly_images]]
major = 10
minor = 1
version = "10.1.0"
release_version = "10.1.0.Final"
core_version = "2.2.0"
core_release_version = "2.2.0.Final"
image_tag = "10.1.0.Final"
repository = "docker.io/jboss/wildfly"
platforms = []

[[wildfly_images]]
major = 11
minor = 0
version = "11.0.0"
release_version = "11.0.0.Final"
core_version = "3.0.8"
core_release_version = "3.0.8.Final"
image_tag = "11.0.0.Final"
repository = "docker.io/jboss/wildfly"
platforms = []

[[wildfly_images]]
major = 12
minor = 0
version = "12.0.0"
release_version = "12.0.0.Final"
core_version = "4.0.0"
core_release_version = "4.0.0.Final"
image_tag = "12.0.0.Final"
repository = "docker.io/jboss/wildfly"
platforms = []

[[wildfly_images]]
major = 13
minor = 0
version = "13.0.0"
release_version = "13.0.0.Final"
core_version = "5.0.0"
core_release_version = "5.0.0.Final"
image_tag = "13.0.0.Final"
repository = "docker.io/jboss/wildfly"
platforms = []

[[wildfly_images]]
major = 14
minor = 0
version = "14.0.1"
release_version = "14.0.1.Final"
core_version = "6.0.2"
core_release_version = "6.0.2.Final"
image_tag = "14.0.1.Final"
repository = "docker.io/jboss/wildfly"
platforms = []

[[wildfly_images]]
major = 15
minor = 0
version = "15.0.1"
release_version = "15.0.1.Final"
core_version = "7.0.0"
core_release_version = "7.0.0.Final"
image_tag = "15.0.1.Final"
repository = "docker.io/jboss/wildfly"
platforms = []

[[wildfly_images]]
major = 16
minor = 0
version = "16.0.0"
release_version = "16.0.0.Final"
core_version = "8.0.0"
core_release_version = "8.0.0.Final"
image_tag = "16.0.0.Final"
repository = "docker.io/jboss/wildfly"
platforms = []

[[wildfly_images]]
major = 17
minor = 0
version = "17.0.1"
release_version = "17.0.1.Final"
core_version = "9.0.2"
core_release_version = "9.0.2.Final"
image_tag = "17.0.1.Final"
repository = "docker.io/jboss/wildfly"
platforms = []

[[wildfly_images]]
major = 18
minor = 0
version = "18.0.1"
release_version = "18.0.1.Final"
core_version = "10.0.3"
core_release_version = "10.0.3.Final"
image_tag = "18.0.1.Final"
repository = "docker.io/jboss/wildfly"
platforms = []

[[wildfly_images]]
major = 19
minor = 0
version = "19.0.0"
release_version = "19.0.0.Final"
core_version = "11.0.0"
core_release_version = "11.0.0.Final"
image_tag = "19.0.0.Final"
repository = "docker.io/jboss/wildfly"
platforms = []

[[wildfly_images]]
major = 19
minor = 1
version = "19.1.0"
release_version = "19.1.0.Final"
core_version = "11.1.1"
core_release_version = "11.1.1.Final"
image_tag = "19.1.0.Final"
repository = "docker.io/jboss/wildfly"
platforms = []

[[wildfly_images]]
major = 20
minor = 0
version = "20.0.1"
release_version = "20.0.1.Final"
core_version = "12.0.3"
core_release_version = "12.0.3.Final"
image_tag = "20.0.1.Final"
repository = "docker.io/jboss/wildfly"
platforms = []

[[wildfly_images]]
major = 21
minor = 0
version = "21.0.2"
release_version = "21.0.2.Final"
core_version = "13.0.3"
core_release_version = "13.0.3.Final"
image_tag = "21.0.2.Final"
repository = "docker.io/jboss/wildfly"
platforms = []

[[wildfly_images]]
major = 22
minor = 0
version = "22.0.1"
release_version = "22.0.1.Final"
core_version = "14.0.1"
core_release_version = "14.0.1.Final"
image_tag = "22.0.1.Final"
repository = "docker.io/jboss/wildfly"
platforms = []

[[wildfly_images]]
major = 23
minor = 0
version = "23.0.2"
release_version = "23.0.2.Final"
core_version = "15.0.1"
core_release_version = "15.0.1.Final"
image_tag = "23.0.2.Final"
repository = "quay.io/wildfly/wildfly"
platforms = []

[[wildfly_images]]
major = 24
minor = 0
version = "24.0.0"
release_version = "24.0.0.Final"
core_version = "16.0.0"
core_release_version = "16.0.0.Final"
image_tag = "24.0.0.Final"
repository = "quay.io/wildfly/wildfly"
platforms = []

[[wildfly_images]]
major = 25
minor = 0
version = "25.0.1"
release_version = "25.0.1.Final"
core_version = "17.0.3"
core_release_version = "17.0.3.Final"
image_tag = "25.0.1.Final"
repository = "quay.io/wildfly/wildfly"
platforms = []

[[wildfly_images]]
major = 26
minor = 0
version = "26.0.1"
release_version = "26.0.1.Final"
core_version = "18.0.4"
core_release_version = "18.0.4.Final"
image_tag = "26.0.1.Final"
repository = "quay.io/wildfly/wildfly"
platforms = []

[[wildfly_images]]
major = 26
minor = 1
version = "26.1.3"
release_version = "26.1.3.Final"
core_version = "18.1.2"
core_release_version = "18.1.2.Final"
image_tag = "26.1.3.Final-jdk17"
repository = "quay.io/wildfly/wildfly"
platforms = ["linux/amd64", "linux/arm64"]

[[wildfly_images]]
major = 27
minor = 0
version = "27.0.1"
release_version = "27.0.1.Final"
core_version = "19.0.1"
core_release_version = "19.0.1.Final"
image_tag = "27.0.1.Final-jdk19"
repository = "quay.io/wildfly/wildfly"
platforms = ["linux/amd64", "linux/arm64"]

[[wildfly_images]]
major = 28
minor = 0
version = "28.0.1"
release_version = "28.0.1.Final"
core_version = "20.0.2"
core_release_version = "20.0.2.Final"
image_tag = "28.0.1.Final-jdk20"
repository = "quay.io/wildfly/wildfly"
platforms = ["linux/amd64", "linux/arm64"]

[[wildfly_images]]
major = 29
minor = 0
version = "29.0.1"
release_version = "29.0.1.Final"
core_version = "21.1.1"
core_release_version = "21.1.1.Final"
image_tag = "29.0.1.Final-jdk20"
repository = "quay.io/wildfly/wildfly"
platforms = ["linux/amd64", "linux/arm64"]

[[wildfly_images]]
major = 30
minor = 0
version = "30.0.1"
release_version = "30.0.1.Final"
core_version = "22.0.2"
core_release_version = "22.0.2.Final"
image_tag = "30.0.1.Final-jdk20"
repository = "quay.io/wildfly/wildfly"
platforms = ["linux/amd64", "linux/arm64"]

[[wildfly_images]]
major = 31
minor = 0
version = "31.0.1"
release_version = "31.0.1.Final"
core_version = "23.0.3"
core_release_version = "23.0.3.Final"
image_tag = "31.0.1.Final-jdk20"
repository = "quay.io/wildfly/wildfly"
platforms = ["linux/amd64", "linux/arm64"]

[[wildfly_images]]
major = 32
minor = 0
version = "32.0.1"
release_version = "32.0.1.Final"
core_version = "24.0.1"
core_release_version = "24.0.1.Final"
image_tag = "32.0.1.Final-jdk21"
repository = "quay.io/wildfly/wildfly"
platforms = ["linux/amd64", "linux/arm64", "linux/s390x"]

[[wildfly_images]]
major = 33
minor = 0
version = "33.0.2"
release_version = "33.0.2.Final"
core_version = "25.0.2"
core_release_version = "25.0.2.Final"
image_tag = "33.0.2.Final-jdk21"
repository = "quay.io/wildfly/wildfly"
platforms = ["linux/amd64", "linux/arm64", "linux/s390x", "linux/ppc64le"]

[[wildfly_images]]
major = 34
minor = 0
version = "34.0.1"
release_version = "34.0.1.Final"
core_version = "26.0.1"
core_release_version = "26.0.1.Final"
image_tag = "34.0.1.Final-jdk21"
repository = "quay.io/wildfly/wildfly"
platforms = ["linux/amd64", "linux/arm64", "linux/s390x", "linux/ppc64le"]

[[wildfly_images]]
major = 35
minor = 0
version = "35.0.1"
release_version = "35.0.1.Final"
core_version = "27.0.1"
core_release_version = "27.0.1.Final"
image_tag = "35.0.1.Final-jdk21"
repository = "quay.io/wildfly/wildfly"
platforms = ["linux/amd64", "linux/arm64", "linux/s390x", "linux/ppc64le"]

[[wildfly_images]]
major = 36
minor = 0
version = "36.0.1"
release_version = "36.0.1.Final"
core_version = "28.0.1"
core_release_version = "28.0.1.Final"
image_tag = "36.0.1.Final-jdk21"
repository = "quay.io/wildfly/wildfly"
platforms = ["linux/amd64", "linux/arm64", "linux/s390x", "linux/ppc64le"]

[[wildfly_images]]
major = 37
minor = 0
version = "37.0.1"
release_version = "37.0.1.Final"
core_version = "29.0.1"
core_release_version = "29.0.1.Final"
image_tag = "37.0.1.Final-jdk21"
repository = "quay.io/wildfly/wildfly"
platforms = ["linux/amd64", "linux/arm64", "linux/s390x", "linux/ppc64le"]

[[wildfly_images]]
major = 38
minor = 0
version = "38.0.1"
release_version = "38.0.1.Final"
core_version = "30.0.0"
core_release_version = "30.0.0.Final"
image_tag = "38.0.1.Final-jdk21"
repository = "quay.io/wildfly/wildfly"
platforms = ["linux/amd64", "linux/arm64", "linux/s390x", "linux/ppc64le"]

[[wildfly_images]]
major = 39
minor = 0
version = "39.0.1"
release_version = "39.0.1.Final"
core_version = "31.0.3"
core_release_version = "31.0.3.Final"
image_tag = "39.0.1.Final-2-jdk21"
repository = "quay.io/wildfly/wildfly"
platforms = ["linux/amd64", "linux/arm64", "linux/s390x", "linux/ppc64le"]
